const newInput = document.querySelector("#new")
const submitInput = document.querySelector(".button")
const todoContent = document.querySelector(".wrap")
const completedTask = document.querySelector(".count1")
const totalTask = document.querySelector(".count2")
const remainingTask = document.querySelector(".count3")
